name: "MurphySec code scan"
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: murphysec/murphysec:github
    steps:
      - name: Checkout_Actions
        uses: actions/checkout@v3
      - name: Code scan
        run: murphysec  scan . --token ${{ secrets.MURPHYSEC_TOKEN }} --json >scan_results.json
      - name: Format data
        run: python3 github_actions_format.py
      - name: Check if file exists
        run: |
          if [ -f "results.sarif" ]; then
            echo "file_exists=true" >> $GITHUB_ENV
          else
            echo "file_exists=false" >> $GITHUB_ENV
          fi
      - name: Upload SARIF file
        if: env.file_exists == 'true'
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
